"""Add meal randomizer tables

Revision ID: 2026_01_24_meal_randomizer
Revises: 1d9a002d7234
Create Date: 2026-01-24 18:43:48.000000

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "2026_01_24_meal_randomizer"
down_revision: str | None = "1d9a002d7234"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create recipe_ratings table
    op.create_table(
        "recipe_ratings",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("rating", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], name="fk_recipe_ratings_recipe_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_recipe_ratings_user_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "recipe_id", name="user_id_recipe_id_key"),
    )
    op.create_index("ix_recipe_ratings_user_id", "recipe_ratings", ["user_id"], unique=False)

    # Create randomizer_templates table
    op.create_table(
        "randomizer_templates",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("template_name", sa.String(length=255), nullable=False),
        sa.Column("week_plan_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_randomizer_templates_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_randomizer_templates_user_id", "randomizer_templates", ["user_id"], unique=False)

    # Create randomizer_preferences table
    op.create_table(
        "randomizer_preferences",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("filter_defaults", sa.JSON(), nullable=True),
        sa.Column("recipe_candidate_cap", sa.Integer(), nullable=False, server_default="200"),
        sa.Column("avoid_repeat_days", sa.Integer(), nullable=False, server_default="7"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_randomizer_preferences_user_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="user_id_key"),
    )
    op.create_index("ix_randomizer_preferences_user_id", "randomizer_preferences", ["user_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_randomizer_preferences_user_id", table_name="randomizer_preferences")
    op.drop_table("randomizer_preferences")

    op.drop_index("ix_randomizer_templates_user_id", table_name="randomizer_templates")
    op.drop_table("randomizer_templates")

    op.drop_index("ix_recipe_ratings_user_id", table_name="recipe_ratings")
    op.drop_table("recipe_ratings")

    # ### end Alembic commands ###
